### ISSUE TITLE
Numerous issues with the codestyle associated with your code

### ISSUE THREAD

**Issue by relative** [pxldotblue/backend-but-better#1]
Hi!

While looking over at your source I've seen numerous issues that should be addressed:

## Mixed indentation
Taking a look at [/index.js](https://github.com/pxldotblue/backend-but-better/blob/ef8ae9ccb85bc7064deca87aeba38121c165eadb/index.js) we will observe that you prefer to use 2 spaces here, however in [/routes/dox.route.js](https://github.com/pxldotblue/backend-but-better/blob/ef8ae9ccb85bc7064deca87aeba38121c165eadb/routes/dox.route.js) you are using **4** spaces in lieu of tabs.

This is not healthy for collaboration and should be solved.

## Mixed quotes
Taking a look at [/index.js](https://github.com/pxldotblue/backend-but-better/blob/ef8ae9ccb85bc7064deca87aeba38121c165eadb/index.js) and [/routes/dox.route.js](https://github.com/pxldotblue/backend-but-better/blob/ef8ae9ccb85bc7064deca87aeba38121c165eadb/routes/dox.route.js) we will observe that there are numerous instances where strings are surrounded in different quote symbols (`, ', and ")

This is not healthy for collaboration and should be solved.

I hope to see the issues I've reported resolved by you.

Best regards,
relative

**Comment by q-woen-p** [comment]
thanks for your input gdem skidem i will get my g to look into this and fix it after his wank <3

love, 
woen

**Comment by Stroketon** [comment]
gdem skidem

**Comment by connuh** [comment]
Another issue is the hardcoded values, what if I am running this on a Linux box without root / sudo?
Do you guys not know about the > 1024 port limit for user accounts on Linux? How else will I dox people without this, please fix.

**Comment by environmentfile** [comment]
Thank you very much for your assistance and interest in our project. I will look into this and fix the issues you've mentioned.

**Comment by connuh** [comment]
No? You will fix them, don't make me open a pull request.

**Comment by q-woen-p** [comment]
> Another issue is the hardcoded values, what if I am running this on a Linux box without root / sudo?
> Do you guys not know about the > 1024 port limit for user accounts on Linux? How else will I dox people without this, please fix.

im sorry to hear that this is stopping you from doxxing, environment will look into the issue and fix it uwu >~<

love, 
woen

**Comment by connuh** [comment]
> > Another issue is the hardcoded values, what if I am running this on a Linux box without root / sudo?
> > Do you guys not know about the > 1024 port limit for user accounts on Linux? How else will I dox people without this, please fix.
> 
> im sorry to hear that this is stopping you from doxxing, environment will look into the issue and fix it uwu >~<
> 
> love,
> woen

meow for me, kitten. uwu

**Comment by environmentfile** [comment]
> Another issue is the hardcoded values, what if I am running this on a Linux box without root / sudo?
> Do you guys not know about the > 1024 port limit for user accounts on Linux? How else will I dox people without this, please fix.

I would like to apologize for my co-workers unprofessional behavior. Yes,we are aware of this limitation,however we have not had the time to use env vars for the ports. This will be fixed in the next update.

Cheers,
environment

**Comment by connuh** [comment]
> > Another issue is the hardcoded values, what if I am running this on a Linux box without root / sudo?
> > Do you guys not know about the > 1024 port limit for user accounts on Linux? How else will I dox people without this, please fix.
> 
> I would like to apologize for my co-workers unprofessional behavior. Yes,we are aware of this limitation,however we have not had the time to use env vars for the ports. This will be fixed in the next update.
> 
> Cheers,
> environment

Appreciate it, my driller.

Now hurry the fuck up cunt <3

**Comment by vanility0001** [comment]
drilla*

**Comment by connuh** [comment]
soz babe xx

**Comment by vanility0001** [comment]
its ok uwu

**Comment by q-woen-p** [comment]
uwu send willy pics and thigh pics

**Comment by q-woen-p** [comment]
sorry  i meant to say this on discord not here so sorry

**Comment by connuh** [comment]
LOL

**Comment by connuh** [comment]
woen doin up oppblock and getting willy pics

**Comment by connuh** [comment]
Why the fuck cunt

**Comment by q-woen-p** [comment]
bad boy >~<

**Comment by q-woen-p** [comment]
(fem)boy*

**Comment by environmentfile** [comment]
> Why the fuck cunt

Because, It was unneeded. I deleted it because it had nothing to do with fixing the issues.

**Comment by vanility0001** [comment]
> > Why the fuck cunt
> 
> Because, It was unneeded. I deleted it because it had nothing to do with fixing the issues.

you're gay

**Comment by connuh** [comment]
![image](https://user-images.githubusercontent.com/58452210/105160873-a3bef980-5b08-11eb-8758-f2d2bab36f28.png)

**Comment by q-woen-p** [comment]
![image](https://user-images.githubusercontent.com/73317311/105160942-b9ccba00-5b08-11eb-8574-c47f6380151f.png)

**Comment by vanility0001** [comment]
delete that please

**Comment by connuh** [comment]
![image](https://user-images.githubusercontent.com/58452210/105161057-da950f80-5b08-11eb-9ab1-2223ff20c3c4.png)

**Comment by vanility0001** [comment]
thanks

**Comment by connuh** [comment]
hahaha ur gay faggot

**Comment by environmentfile** [comment]
![image](https://user-images.githubusercontent.com/77233222/105161132-e27f9000-5ac5-11eb-82b3-3bc7e3d70913.png)

**Comment by vanility0001** [comment]
STOPPPPPPPPPPPP

**Comment by q-woen-p** [comment]
i like willy in my bum

**Comment by connuh** [comment]
nyaa~

**Comment by environmentfile** [comment]
@relative @connuh I have fixed the issues you mentioned. Thank you very much for your interest in our project.
